import fs from 'fs'
import path from 'path'

interface SourceDay {
  name: string
  date: string
  isOffDay: boolean
}

interface SourceData {
  year: number
  days: SourceDay[]
}

type CompactDay = [number, number, 0 | 1]

function buildCompactData() {
  const dataDir = path.join(__dirname, '../data')
  const files = fs
    .readdirSync(dataDir)
    .filter(f => /20\d{2}\.json$/.test(f))
    .sort()

  // Collect all holiday names and data
  const nameSet = new Set<string>()
  const yearData: Record<number, SourceDay[]> = {}

  for (const file of files) {
    const content = fs.readFileSync(path.join(dataDir, file), 'utf8')
    const json: SourceData = JSON.parse(content)

    // Organize data by year from date (not the file's year field)
    json.days.forEach(day => {
      const dateYear = parseInt(day.date.split('-')[0])
      if (!yearData[dateYear]) {
        yearData[dateYear] = []
      }
      yearData[dateYear].push(day)
      nameSet.add(day.name)
    })
  }

  // Create name index
  const names = Array.from(nameSet).sort()
  const nameToIndex = new Map(names.map((n, i) => [n, i]))

  // Convert to compact format
  const compactData: Record<number, CompactDay[]> = {}

  for (const [year, days] of Object.entries(yearData)) {
    compactData[+year] = days.map(day => {
      const [, month, dayNum] = day.date.split('-')
      const monthDay = parseInt(month + dayNum)
      return [nameToIndex.get(day.name)!, monthDay, day.isOffDay ? 1 : 0] as CompactDay
    })
  }

  // Generate TypeScript file
  const output = `// Auto-generated by scripts/build-data.ts - DO NOT EDIT

export const HOLIDAY_NAMES = ${JSON.stringify(names)} as const

export type CompactDay = [number, number, 0 | 1]

export const HOLIDAY_DATA: Record<number, CompactDay[]> = ${JSON.stringify(compactData)}
`

  const outputPath = path.join(__dirname, '../src/holiday-data.ts')
  fs.writeFileSync(outputPath, output, 'utf8')

  // Statistics
  const totalEntries = Object.values(compactData).reduce((sum, days) => sum + days.length, 0)
  console.log('✓ Generated compact holiday data')
  console.log(`  Names: ${names.length}`)
  console.log(`  Years: ${Object.keys(compactData).length}`)
  console.log(`  Total entries: ${totalEntries}`)
}

buildCompactData()
