import fs from 'fs'
import path from 'path'

interface SourceDay {
  name: string
  date: string
  isOffDay: boolean
}

interface SourceData {
  year: number
  days: SourceDay[]
}

type CompactDay = [number, number, 0 | 1]

const DATE_PATTERN = /^(\d{4})-(\d{2})-(\d{2})$/

function parseDate(file: string, raw: string): { year: number; month: number; day: number } {
  const match = raw.match(DATE_PATTERN)
  if (!match) {
    throw new Error(`Invalid date "${raw}" in ${file}: expected YYYY-MM-DD`)
  }
  const year = Number(match[1])
  const month = Number(match[2])
  const day = Number(match[3])
  if (month < 1 || month > 12 || day < 1 || day > 31) {
    throw new Error(`Out-of-range date "${raw}" in ${file}`)
  }
  return { year, month, day }
}

interface ParsedEntry {
  day: SourceDay
  month: number
  day_: number
}

function buildCompactData() {
  const dataDir = path.join(__dirname, '../data')
  const files = fs
    .readdirSync(dataDir)
    .filter(f => /20\d{2}\.json$/.test(f))
    .sort()

  const nameSet = new Set<string>()
  const yearData: Record<number, ParsedEntry[]> = {}

  for (const file of files) {
    const content = fs.readFileSync(path.join(dataDir, file), 'utf8')
    const json: SourceData = JSON.parse(content)

    for (const day of json.days) {
      const { year, month, day: dayNum } = parseDate(file, day.date)
      if (!yearData[year]) yearData[year] = []
      yearData[year].push({ day, month, day_: dayNum })
      nameSet.add(day.name)
    }
  }

  const names = Array.from(nameSet).sort()
  const nameToIndex = new Map(names.map((n, i) => [n, i]))

  const compactData: Record<number, CompactDay[]> = {}
  for (const [year, entries] of Object.entries(yearData)) {
    compactData[+year] = entries.map(({ day, month, day_ }) => {
      const nameIndex = nameToIndex.get(day.name)
      if (nameIndex === undefined) {
        throw new Error(`Name "${day.name}" missing from index — should be unreachable`)
      }
      return [nameIndex, month * 100 + day_, day.isOffDay ? 1 : 0]
    })
  }

  const output = `// Auto-generated by scripts/build-data.ts - DO NOT EDIT

export const HOLIDAY_NAMES = ${JSON.stringify(names)} as const

export type CompactDay = [number, number, 0 | 1]

export const HOLIDAY_DATA: Record<number, CompactDay[]> = ${JSON.stringify(compactData)}
`

  const outputPath = path.join(__dirname, '../src/holiday-data.ts')
  fs.writeFileSync(outputPath, output, 'utf8')

  const totalEntries = Object.values(compactData).reduce((sum, days) => sum + days.length, 0)
  console.log('✓ Generated compact holiday data')
  console.log(`  Names: ${names.length}`)
  console.log(`  Years: ${Object.keys(compactData).length}`)
  console.log(`  Total entries: ${totalEntries}`)
}

buildCompactData()
