---
on:
  push:
    branches: [master]
  pull_request:
name: test

jobs:
  Vitest:
    name: Vitest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          submodules: true

      - name: Install Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 24.16.0

      - uses: pnpm/action-setup@v6.0.8
        name: Install pnpm
        with:
          version: 11.6.0
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v5.0.5
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Generate holiday data
        run: pnpm build:data

      - run: pnpm run test --run

  Format:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0

      - name: Install Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 24.16.0

      - uses: pnpm/action-setup@v6.0.8
        name: Install pnpm
        with:
          version: 11.6.0
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v5.0.5
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - run: pnpm run format:check
